"""
Improvement Proposal for the Adaptive Evolution Engine.

This module provides the ImprovementProposal class for representing and managing
improvement proposals generated by the Adaptive Evolution Engine.
"""

import logging
import uuid
from typing import Dict, Any, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class ImprovementProposal:
    """
    Represents a proposed improvement to the Digital Twin.
    
    Encapsulates all information related to a proposed improvement, including
    its description, implementation plan, expected benefits, risk assessment,
    and evaluation results.
    """
    
    def __init__(self, 
                 proposal_id: str = None,
                 component: str = "",
                 description: str = "",
                 implementation_plan: List[Dict[str, Any]] = None,
                 expected_benefits: List[str] = None,
                 risk_assessment: Dict[str, Any] = None,
                 priority: float = 0.5):
        """
        Initialize an improvement proposal.
        
        Args:
            proposal_id: Unique identifier for the proposal (generated if None)
            component: Component to be improved
            description: Description of the improvement
            implementation_plan: List of implementation steps
            expected_benefits: List of expected benefits
            risk_assessment: Risk assessment dictionary
            priority: Priority score (0.0-1.0)
        """
        self.proposal_id = proposal_id or f"proposal_{uuid.uuid4().hex[:8]}"
        self.component = component
        self.description = description
        self.implementation_plan = implementation_plan or []
        self.expected_benefits = expected_benefits or []
        self.risk_assessment = risk_assessment or {}
        self.priority = priority
        self.status = "proposed"
        self.created_at = datetime.now().isoformat()
        self.updated_at = self.created_at
        self.evaluation_results = {}
        self.implementation_results = {}
        self.metadata = {}
        
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the proposal to a dictionary.
        
        Returns:
            Dictionary representation of the proposal
        """
        return {
            "proposal_id": self.proposal_id,
            "component": self.component,
            "description": self.description,
            "implementation_plan": self.implementation_plan,
            "expected_benefits": self.expected_benefits,
            "risk_assessment": self.risk_assessment,
            "priority": self.priority,
            "status": self.status,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "evaluation_results": self.evaluation_results,
            "implementation_results": self.implementation_results,
            "metadata": self.metadata
        }
        
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ImprovementProposal':
        """
        Create a proposal from a dictionary.
        
        Args:
            data: Dictionary representation of the proposal
            
        Returns:
            ImprovementProposal instance
        """
        proposal = cls(
            proposal_id=data.get("proposal_id"),
            component=data.get("component", ""),
            description=data.get("description", ""),
            implementation_plan=data.get("implementation_plan", []),
            expected_benefits=data.get("expected_benefits", []),
            risk_assessment=data.get("risk_assessment", {}),
            priority=data.get("priority", 0.5)
        )
        proposal.status = data.get("status", "proposed")
        proposal.created_at = data.get("created_at", datetime.now().isoformat())
        proposal.updated_at = data.get("updated_at", datetime.now().isoformat())
        proposal.evaluation_results = data.get("evaluation_results", {})
        proposal.implementation_results = data.get("implementation_results", {})
        proposal.metadata = data.get("metadata", {})
        return proposal
    
    def update_status(self, status: str) -> None:
        """
        Update the status of the proposal.
        
        Args:
            status: New status
        """
        self.status = status
        self.updated_at = datetime.now().isoformat()
        logger.info(f"Proposal {self.proposal_id} status updated to {status}")
    
    def add_evaluation_result(self, evaluation_type: str, result: Dict[str, Any]) -> None:
        """
        Add an evaluation result to the proposal.
        
        Args:
            evaluation_type: Type of evaluation
            result: Evaluation result
        """
        self.evaluation_results[evaluation_type] = result
        self.updated_at = datetime.now().isoformat()
        logger.info(f"Added {evaluation_type} evaluation to proposal {self.proposal_id}")
    
    def add_implementation_result(self, result: Dict[str, Any]) -> None:
        """
        Add implementation results to the proposal.
        
        Args:
            result: Implementation result
        """
        self.implementation_results = result
        self.updated_at = datetime.now().isoformat()
        logger.info(f"Added implementation results to proposal {self.proposal_id}")
    
    def add_metadata(self, key: str, value: Any) -> None:
        """
        Add metadata to the proposal.
        
        Args:
            key: Metadata key
            value: Metadata value
        """
        self.metadata[key] = value
        self.updated_at = datetime.now().isoformat()
    
    def is_safe(self) -> bool:
        """
        Check if the proposal has been validated as safe.
        
        Returns:
            True if the proposal is safe, False otherwise
        """
        if "safety_validation" in self.evaluation_results:
            return self.evaluation_results["safety_validation"].get("is_safe", False)
        return False
    
    def get_safety_score(self) -> float:
        """
        Get the safety score of the proposal.
        
        Returns:
            Safety score (0.0-1.0) or 0.0 if not validated
        """
        if "safety_validation" in self.evaluation_results:
            return self.evaluation_results["safety_validation"].get("safety_score", 0.0)
        return 0.0
    
    def get_implementation_success(self) -> bool:
        """
        Check if the implementation was successful.
        
        Returns:
            True if the implementation was successful, False otherwise
        """
        return self.implementation_results.get("success", False)
    
    def get_warnings(self) -> List[str]:
        """
        Get all warnings associated with the proposal.
        
        Returns:
            List of warnings
        """
        warnings = []
        
        # Add safety validation warnings
        if "safety_validation" in self.evaluation_results:
            warnings.extend(self.evaluation_results["safety_validation"].get("warnings", []))
        
        # Add implementation warnings
        if "errors" in self.implementation_results:
            warnings.extend(self.implementation_results["errors"])
        
        return warnings
    
    def get_recommendations(self) -> List[str]:
        """
        Get all recommendations associated with the proposal.
        
        Returns:
            List of recommendations
        """
        recommendations = []
        
        # Add safety validation recommendations
        if "safety_validation" in self.evaluation_results:
            recommendations.extend(self.evaluation_results["safety_validation"].get("recommendations", []))
        
        # Add implementation evaluation recommendations
        if "implementation_evaluation" in self.evaluation_results:
            recommendations.extend(self.evaluation_results["implementation_evaluation"].get("recommendations", []))
        
        return recommendations