"""
Safety Validator for the Adaptive Evolution Engine.

This module provides safety validation capabilities for improvement proposals
generated by the Adaptive Evolution Engine.
"""

import logging
import sys
import os
from typing import Dict, Any, List, Optional, Tuple
import importlib.util
import json
import uuid
from datetime import datetime
import asyncio

logger = logging.getLogger(__name__)


class SafetyValidator:
    """
    Validates the safety of improvement proposals.
    
    Ensures that proposed improvements to the Digital Twin meet safety requirements
    across multiple dimensions including data integrity, user privacy, system stability,
    and behavioral consistency.
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """
        Initialize the safety validator.
        
        Args:
            config: Configuration dictionary
        """
        self.config = config or {}
        self.safety_thresholds = self.config.get("safety_thresholds", {
            "data_integrity": 0.8,
            "user_privacy": 0.9,
            "system_stability": 0.8,
            "behavioral_consistency": 0.7
        })
        self.validation_history = []
        logger.info("Safety Validator initialized")
        
    async def validate_proposal(self, proposal: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate the safety of an improvement proposal.
        
        Args:
            proposal: The improvement proposal to validate
            
        Returns:
            Validation results dictionary
        """
        # Initialize validation results
        validation_results = {
            "is_safe": True,
            "safety_score": 0.0,
            "safety_aspects": {},
            "warnings": [],
            "recommendations": [],
            "validation_id": str(uuid.uuid4()),
            "timestamp": datetime.now().isoformat()
        }
        
        # Validate data integrity
        data_integrity_score = await self._validate_data_integrity(proposal)
        validation_results["safety_aspects"]["data_integrity"] = data_integrity_score
        
        # Validate user privacy
        user_privacy_score = await self._validate_user_privacy(proposal)
        validation_results["safety_aspects"]["user_privacy"] = user_privacy_score
        
        # Validate system stability
        system_stability_score = await self._validate_system_stability(proposal)
        validation_results["safety_aspects"]["system_stability"] = system_stability_score
        
        # Validate behavioral consistency
        behavioral_consistency_score = await self._validate_behavioral_consistency(proposal)
        validation_results["safety_aspects"]["behavioral_consistency"] = behavioral_consistency_score
        
        # Calculate overall safety score
        safety_scores = validation_results["safety_aspects"]
        validation_results["safety_score"] = sum(safety_scores.values()) / len(safety_scores)
        
        # Check if any aspect fails to meet the threshold
        for aspect, score in safety_scores.items():
            threshold = self.safety_thresholds.get(aspect, 0.7)
            if score < threshold:
                validation_results["is_safe"] = False
                validation_results["warnings"].append(
                    f"{aspect} score ({score:.2f}) is below the threshold ({threshold:.2f})"
                )
                validation_results["recommendations"].append(
                    self._get_recommendation_for_aspect(aspect, score, proposal)
                )
        
        # Add to validation history
        self.validation_history.append({
            "validation_id": validation_results["validation_id"],
            "proposal_id": proposal.get("proposal_id", "unknown"),
            "timestamp": validation_results["timestamp"],
            "is_safe": validation_results["is_safe"],
            "safety_score": validation_results["safety_score"]
        })
        
        return validation_results
    
    async def validate_implementation(self, proposal: Dict[str, Any], 
                                    implementation_plan: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Validate the safety of an implementation plan.
        
        Args:
            proposal: The improvement proposal
            implementation_plan: The implementation plan to validate
            
        Returns:
            Validation results dictionary
        """
        # Initialize validation results
        validation_results = {
            "is_safe": True,
            "safety_score": 0.0,
            "step_validations": [],
            "warnings": [],
            "recommendations": [],
            "validation_id": str(uuid.uuid4()),
            "timestamp": datetime.now().isoformat()
        }
        
        # Validate each step in the implementation plan
        for i, step in enumerate(implementation_plan):
            step_validation = await self._validate_implementation_step(step, proposal)
            validation_results["step_validations"].append({
                "step_index": i,
                "step_description": step.get("description", f"Step {i+1}"),
                "is_safe": step_validation["is_safe"],
                "safety_score": step_validation["safety_score"],
                "warnings": step_validation["warnings"]
            })
            
            # If any step is unsafe, the whole implementation is unsafe
            if not step_validation["is_safe"]:
                validation_results["is_safe"] = False
                validation_results["warnings"].extend([
                    f"Step {i+1}: {warning}" for warning in step_validation["warnings"]
                ])
                validation_results["recommendations"].extend([
                    f"Step {i+1}: {recommendation}" for recommendation in step_validation["recommendations"]
                ])
        
        # Calculate overall safety score
        if validation_results["step_validations"]:
            validation_results["safety_score"] = sum(
                step["safety_score"] for step in validation_results["step_validations"]
            ) / len(validation_results["step_validations"])
        
        # Add to validation history
        self.validation_history.append({
            "validation_id": validation_results["validation_id"],
            "proposal_id": proposal.get("proposal_id", "unknown"),
            "timestamp": validation_results["timestamp"],
            "is_safe": validation_results["is_safe"],
            "safety_score": validation_results["safety_score"],
            "type": "implementation"
        })
        
        return validation_results
    
    async def get_validation_history(self) -> List[Dict[str, Any]]:
        """
        Get the validation history.
        
        Returns:
            List of validation history entries
        """
        return self.validation_history
    
    async def _validate_data_integrity(self, proposal: Dict[str, Any]) -> float:
        """
        Validate the data integrity aspects of a proposal.
        
        Args:
            proposal: The improvement proposal to validate
            
        Returns:
            Data integrity safety score (0.0-1.0)
        """
        # Base score
        score = 0.8
        
        # Check if the proposal affects data storage or processing
        component = proposal.get("component", "").lower()
        description = proposal.get("description", "").lower()
        if any(term in component or term in description for term in ["data", "storage", "memory", "database"]):
            # Check if the implementation plan includes data validation steps
            implementation_plan = proposal.get("implementation_plan", [])
            has_validation = any("validate" in str(step).lower() for step in implementation_plan)
            if not has_validation:
                score -= 0.2
            
            # Check if the implementation plan includes rollback steps
            has_rollback = any("rollback" in str(step).lower() for step in implementation_plan)
            if not has_rollback:
                score -= 0.1
        
        # Check risk assessment
        risk_assessment = proposal.get("risk_assessment", {})
        if "data_integrity" in risk_assessment:
            risk_level = risk_assessment["data_integrity"]
            if isinstance(risk_level, (int, float)) and risk_level > 0.5:
                score -= (risk_level - 0.5) * 0.4
        
        return max(0.0, min(1.0, score))
    
    async def _validate_user_privacy(self, proposal: Dict[str, Any]) -> float:
        """
        Validate the user privacy aspects of a proposal.
        
        Args:
            proposal: The improvement proposal to validate
            
        Returns:
            User privacy safety score (0.0-1.0)
        """
        # Base score
        score = 0.9
        
        # Check if the proposal affects user data
        component = proposal.get("component", "").lower()
        description = proposal.get("description", "").lower()
        privacy_keywords = ["user", "personal", "data", "privacy", "information"]
        if any(keyword in component or keyword in description for keyword in privacy_keywords):
            # Check if the implementation plan includes privacy protection steps
            implementation_plan = proposal.get("implementation_plan", [])
            has_privacy_protection = any("privacy" in str(step).lower() for step in implementation_plan)
            if not has_privacy_protection:
                score -= 0.3
            
            # Check if the implementation plan includes anonymization steps
            has_anonymization = any("anonymiz" in str(step).lower() for step in implementation_plan)
            if not has_anonymization:
                score -= 0.2
        
        # Check risk assessment
        risk_assessment = proposal.get("risk_assessment", {})
        if "user_privacy" in risk_assessment:
            risk_level = risk_assessment["user_privacy"]
            if isinstance(risk_level, (int, float)) and risk_level > 0.3:
                score -= (risk_level - 0.3) * 0.6
        
        return max(0.0, min(1.0, score))
    
    async def _validate_system_stability(self, proposal: Dict[str, Any]) -> float:
        """
        Validate the system stability aspects of a proposal.
        
        Args:
            proposal: The improvement proposal to validate
            
        Returns:
            System stability safety score (0.0-1.0)
        """
        # Base score
        score = 0.8
        
        # Check if the proposal affects core components
        component = proposal.get("component", "").lower()
        core_components = ["engine", "system", "core", "framework", "infrastructure"]
        if any(comp in component for comp in core_components):
            # Check if the implementation plan includes testing steps
            implementation_plan = proposal.get("implementation_plan", [])
            has_testing = any("test" in str(step).lower() for step in implementation_plan)
            if not has_testing:
                score -= 0.3
            
            # Check if the implementation plan includes monitoring steps
            has_monitoring = any("monitor" in str(step).lower() for step in implementation_plan)
            if not has_monitoring:
                score -= 0.2
            
            # Check if the implementation plan includes rollback steps
            has_rollback = any("rollback" in str(step).lower() for step in implementation_plan)
            if not has_rollback:
                score -= 0.2
        
        # Check risk assessment
        risk_assessment = proposal.get("risk_assessment", {})
        if "system_stability" in risk_assessment:
            risk_level = risk_assessment["system_stability"]
            if isinstance(risk_level, (int, float)) and risk_level > 0.4:
                score -= (risk_level - 0.4) * 0.5
        
        return max(0.0, min(1.0, score))
    
    async def _validate_behavioral_consistency(self, proposal: Dict[str, Any]) -> float:
        """
        Validate the behavioral consistency aspects of a proposal.
        
        Args:
            proposal: The improvement proposal to validate
            
        Returns:
            Behavioral consistency safety score (0.0-1.0)
        """
        # Base score
        score = 0.7
        
        # Check if the proposal affects user-facing components
        component = proposal.get("component", "").lower()
        description = proposal.get("description", "").lower()
        user_facing = ["conversation", "personality", "response", "interaction", "interface"]
        if any(term in component or term in description for term in user_facing):
            # Check if the implementation plan includes consistency validation steps
            implementation_plan = proposal.get("implementation_plan", [])
            has_consistency_check = any("consisten" in str(step).lower() for step in implementation_plan)
            if not has_consistency_check:
                score -= 0.2
            
            # Check if the implementation plan includes user testing steps
            has_user_testing = any(("user" in str(step).lower() and "test" in str(step).lower()) for step in implementation_plan)
            if not has_user_testing:
                score -= 0.2
        
        # Check risk assessment
        risk_assessment = proposal.get("risk_assessment", {})
        if "behavioral_consistency" in risk_assessment:
            risk_level = risk_assessment["behavioral_consistency"]
            if isinstance(risk_level, (int, float)) and risk_level > 0.3:
                score -= (risk_level - 0.3) * 0.5
        
        return max(0.0, min(1.0, score))
    
    async def _validate_implementation_step(self, step: Dict[str, Any], 
                                          proposal: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate the safety of an implementation step.
        
        Args:
            step: The implementation step to validate
            proposal: The parent proposal
            
        Returns:
            Step validation results
        """
        # Initialize step validation results
        step_validation = {
            "is_safe": True,
            "safety_score": 0.8,  # Default to relatively safe
            "warnings": [],
            "recommendations": []
        }
        
        # Check step type
        step_type = step.get("step_type", "").lower()
        
        # Validate based on step type
        if step_type == "modify":
            # Modifications are higher risk
            step_validation["safety_score"] -= 0.1
            
            # Check if the step has clear parameters
            if not step.get("parameters"):
                step_validation["safety_score"] -= 0.1
                step_validation["warnings"].append("Modification step lacks clear parameters")
                step_validation["recommendations"].append("Add specific parameters to the modification step")
            
            # Check if the component being modified is critical
            component = proposal.get("component", "").lower()
            critical_components = ["core", "engine", "system", "framework"]
            if any(comp in component for comp in critical_components):
                step_validation["safety_score"] -= 0.1
                step_validation["warnings"].append("Modification affects a critical component")
                step_validation["recommendations"].append("Add additional validation steps for critical component changes")
        
        elif step_type == "deploy":
            # Deployments are higher risk
            step_validation["safety_score"] -= 0.1
            
            # Check if there's a monitoring step after deployment
            implementation_plan = proposal.get("implementation_plan", [])
            step_index = next((i for i, s in enumerate(implementation_plan) if s == step), -1)
            has_monitoring_after = False
            if step_index >= 0 and step_index < len(implementation_plan) - 1:
                has_monitoring_after = any("monitor" in str(s).lower() for s in implementation_plan[step_index+1:])
            
            if not has_monitoring_after:
                step_validation["safety_score"] -= 0.2
                step_validation["warnings"].append("Deployment lacks subsequent monitoring")
                step_validation["recommendations"].append("Add monitoring steps after deployment")
        
        # Check if the step has a clear description
        if not step.get("description"):
            step_validation["safety_score"] -= 0.1
            step_validation["warnings"].append("Step lacks clear description")
            step_validation["recommendations"].append("Add a detailed description to the step")
        
        # Check if the step has a clear action
        if not step.get("action"):
            step_validation["safety_score"] -= 0.1
            step_validation["warnings"].append("Step lacks clear action")
            step_validation["recommendations"].append("Add a specific action to the step")
        
        # Determine if the step is safe
        if step_validation["safety_score"] < 0.6:
            step_validation["is_safe"] = False
        
        return step_validation
    
    def _get_recommendation_for_aspect(self, aspect: str, score: float, proposal: Dict[str, Any]) -> str:
        """
        Get a recommendation for improving a specific safety aspect.
        
        Args:
            aspect: The safety aspect
            score: The current safety score
            proposal: The proposal being validated
            
        Returns:
            Recommendation string
        """
        if aspect == "data_integrity":
            return "Add explicit data validation and rollback steps to ensure data integrity"
        elif aspect == "user_privacy":
            return "Include privacy protection measures such as data anonymization and access controls"
        elif aspect == "system_stability":
            return "Add comprehensive testing, monitoring, and rollback procedures to maintain system stability"
        elif aspect == "behavioral_consistency":
            return "Include consistency validation and user testing to ensure behavioral consistency"
        else:
            return f"Improve {aspect} safety measures in the proposal"